In [1]:
import numpy as np

In [3]:
a =[1,2,3,4]
b=[5,6,7,8]
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
[a[i]+b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [42]:


a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
(a + b)

array([ 6,  8, 10, 12])

In [43]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr[:,1:2]  #start_row:end_row,start_col:end_column

array([[2],
       [5],
       [8]])

In [13]:
arr[1:,:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[:,2:3]

array([[3],
       [6],
       [9]])

In [16]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [17]:
arr[1:,: :2]

array([[4, 6],
       [7, 9]])

In [22]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
a= np.arange(10)

In [29]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [32]:
np.linspace(0,15,5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [33]:
### vector operation with scaler values

In [34]:
a = np.array([1,2,3])
a**2

array([1, 4, 9])

In [36]:
a = np.array([[1,2],[3,4]])
b= np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [37]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [13]:
np.linalg.det(a)

np.float64(-9.51619735392994e-16)

In [14]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [15]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [16]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:

a


array([[1, 2],
       [3, 4]])

In [30]:
a=np.array([1,2,3,4,5,6,7,8,9,10,4,5])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  5])

In [28]:
np.resize(a,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a is b

False

In [31]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  5])]

In [33]:
###copy and views

In [50]:
arr=np.array([1,2,3,4,5,6,7])

In [51]:
b=arr.view()

In [52]:
b[0]=10

In [58]:
arr

array([10,  2,  3,  4,  5,  6])

In [59]:
np.split(a,2)

[array([1, 2]), array([3, 4])]

In [48]:
arr,b

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([5, 6, 7, 8]))

In [60]:
c=arr.copy()

In [61]:
arr,c

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [1]:
####statistics

In [4]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sum(a,axis=0)

array([12, 15, 18])

In [7]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [20]:
def mean(array):
    n=len(array)
    return np.sum(array)/n

In [21]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [18]:
def variance(array):
    m=mean(array)
    n=len(array)
    return np.sum((array-m)**2)/n

In [19]:
variance (np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [ ]:
##minmaxscaler

In [27]:
import numpy as np

a= np.array([10, 20, 30, 40, 50])
a.min()


np.int64(10)

In [28]:
a.max()

np.int64(50)

In [29]:
a.sum()

np.int64(150)

In [30]:
###sigmoid

In [47]:

arr=np.array([4,5,6,2,7,8])
1/(1+np.exp(-a))


array([0.98201379, 0.99330715, 0.99752738, 0.88079708, 0.99908895,
       0.99966465])

In [41]:
##relu

In [36]:
a= np.array([8,9,6,7,5])
np.maximum(0, x)


array([10, 20, 30, 40, 50])

In [48]:
##task1

In [50]:
import numpy as np

scores = np.random.randint(50, 101, (5, 3))

mean = scores.mean(axis=0)

centered = scores - mean

print("Original Scores:\n", scores)
print("\nCentered Scores:\n", centered)


Original Scores:
 [[56 78 67]
 [72 80 89]
 [88 80 94]
 [72 90 82]
 [51 78 64]]

Centered Scores:
 [[-11.8  -3.2 -12.2]
 [  4.2  -1.2   9.8]
 [ 20.2  -1.2  14.8]
 [  4.2   8.8   2.8]
 [-16.8  -3.2 -15.2]]


In [51]:
##task2

In [52]:
import numpy as np
data = np.arange(24)
data = data.reshape(4, 3, 2)
data = data.transpose(0, 2, 1)

print(data.shape)
print(data)


(4, 2, 3)
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
